Uplift/Areas/Customer/Controllers/NewlistingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Uplift.DataAccess.Data.Repository;
using Uplift.Models;

namespace Uplift.Controllers
{
    [Area("Customer")]
    public class NewlistingController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public NewlistingController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item newItem)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Item.Add(newItem);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(newItem);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Uplift/Areas/Customer/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Uplift.Models;
using Uplift.DataAccess.Data;

namespace Uplift.Controllers
{
    [Area("Customer")]
    public class ResultsController : Controller
    {
        private readonly ILogger<ResultsController> _logger;

        public ResultsController(ILogger<ResultsController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<Item> SearchResultsItems = new List<Item>();
            var displayItem = new Item();
            displayItem.Title = "Title1";
            displayItem.Price = 89.99;
            displayItem.ItemDescription = "This is the item description";
            SearchResultsItems.Add(displayItem);
            return View(SearchResultsItems);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Uplift/Areas/Customer/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Uplift.Models;

namespace Uplift.Controllers
{
    [Area("Customer")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;

        public UserController(ILogger<UserController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            dynamic userData = new ExpandoObject();

            List<Item> custItems = new List<Item>();
            var displayItem = new Item();
            displayItem.Title = "Title1";
            displayItem.Price = 89.99;
            displayItem.ItemDescription = "This is the item description";
            custItems.Add(displayItem);

            Customer cust = new Customer();

            cust.Email = "rhunstad@crimson.ua.edu";
            cust.Fname = "Ryland";
            cust.LName = "Hunstad";
            cust.username = "rylandhunstad";
            cust.phoneNumber = 720;

            userData.custItems = custItems;
            userData.customer = cust;

            return View(userData);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Uplift/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>X-Change</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="/assets/img/X180.png" rel="icon">
    <link href="/assets/img/X180.png" rel="apple-touch-icon">
    <link href="/assets/img/MessagesIcon.png" rel="messagesicon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/assets/vendor/aos/aos.css" rel="stylesheet">
    <script type="text/javascript" src="~/js/script.js"></script>

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Moderna - v2.0.1
    * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header">
        <div class="container">

            <div class="logo float-left">
                <!-- col-lg-3 d-flex align-items-stretch -->
                <h1 class="text-light"><a href="/Customer/Home"><span>X-Change</span></a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav class="nav-menu float-right d-none d-lg-block">
                <ul>
                    <li>
                        <form action="">
                            <div class="d-flex align-items-center">
                                <input id="search-query-input-box" type="text" style="margin-top: 3px;width:200px;margin-left:10px;border-radius:4px;" placeholder="Items...">
                                <button class="btn" id="search-query-submit-button" type="reset" style="background-color:#68A4C4;color:#DDECF5;border-radius:10px;line-height:1.65; margin-left:5px;margin-top:3px; padding-left:3px; padding-right:3px">Search</button>
                            </div>
                        </form>
                    </li>

                    <li class="drop-down">
                        <a href="">Shop</a>
                        <ul style="margin-right:15px;">
                            <li>@Html.ActionLink("Supplies", "Index", "Results")</li>
                            <li>@Html.ActionLink("Dorm furniture", "Index", "Results")</li>
                            <li>@Html.ActionLink("Electronics", "Index", "Results")</li>
                            <li>@Html.ActionLink("Men's Clothes", "Index", "Results")</li>
                            <li>@Html.ActionLink("Women's Clothes", "Index", "Results")</li>
                            <li>@Html.ActionLink("Accessories", "Index", "Results")</li>
                            <li>@Html.ActionLink("Services", "Index", "Results")</li>
                            <li>@Html.ActionLink("Browse all", "Index", "Results")</li>
                        </ul>
                    </li>
                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Your Profile", "Index", "User")</li>
                    <li>@Html.ActionLink("Sell!", "Create", "Newlisting")</li>
                    <li><a href="/Customer/User" style="padding-top:0px"><img src="/assets/img/MessagesIcon.png" alt="MessagesIcon" style="width:40px;height:40px;padding-bottom:3px"></a></li>
                </ul>
            </nav>

            <!--
            <div class="d-flex align-items-right">



                <div class="col-lg-3 d-flex align-items-stretch">
                    <ul>
                    </ul>
                </div>

                <div class="col-lg-5 d-flex align-items-stretch">
                    <form action="">
                        <div class="d-flex align-items-center">
                            <input type="text" style="margin-top: 5px;border-radius:3px;" placeholder="Items...">
                            <button class="btn" type="submit" style="background-color:lightblue;line-height:1;margin-top:5px;margin-left:5px">Go</button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-3 d-flex align-items-stretch">
                    <nav class="nav-menu float-right d-none d-lg-block">
                        <ul>
                            <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Your Profile", "Index", "User")</li>
                            <li>@Html.ActionLink("Sell!", "Index", "Newlisting")</li>
                        </ul>
                    </nav>

                </div>
                <div class="col-sm-3 d-flex align-items-stretch"><a href="/Customer/User"><img src="/assets/img/MessagesIcon.png" alt="MessagesIcon" style="width:40px;height:40px;margin-bottom:35px"></a></div>
            </div> -->
        </div>
    </header><!-- End Header -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ======= Footer ======= -->
    <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Site</h4>
                        <ul>
                            <li><a href="https://www.youtube.com/watch?v=oHg5SJYRHA0">ADMIN VIEW (REMOVE LATER!! Just for testing) </a></li>
                            <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Your Profile", "Index", "User")</li>
                            <li>@Html.ActionLink("Sell!", "Index", "Newlisting")</li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Shop</h4>
                        <ul>
                            <li>@Html.ActionLink("Supplies", "Index", "Results")</li>
                            <li>@Html.ActionLink("Dorm furniture", "Index", "Results")</li>
                            <li>@Html.ActionLink("Electronics", "Index", "Results")</li>
                            <li>@Html.ActionLink("Clothes", "Index", "Results")</li>
                            <li>@Html.ActionLink("Services", "Index", "Results")</li>
                            <li>@Html.ActionLink("Browse all", "Index", "Results")</li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h4>Contact Us</h4>
                        <p>
                            1789 Hackberry Ln. <br>
                            Tuscaloosa, AL 35404<br>
                            United States <br><br>
                            <strong>Phone:</strong> +1 720 555 5555<br>
                            <strong>Email:<a href="mailto:rhunstad@crimson.ua.edu" style="color:white"></strong> rhunstad@crimson.ua.edu</a><br>
                        </p>

                    </div>

                    <div class="col-lg-3 col-md-6 footer-info">
                        <h3>About X-Change</h3>
                        <p>X-change aims to give students on campus a medium of exchange for trading goods they no longer need or want, giving all students access to cheap, well sourced goods, reducing waste on campus and increasing spending ability of college students.</p>
                        <div class="social-links mt-3">
                            <a href="https://www.youtube.com/watch?v=oHg5SJYRHA0" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="https://www.youtube.com/watch?v=oHg5SJYRHA0" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="https://www.youtube.com/watch?v=oHg5SJYRHA0" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="https://www.linkedin.com/in/ryland-hunstad-7b8089173/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="/assets/vendor/php-email-form/validate.js"></script>
    <script src="/assets/vendor/venobox/venobox.min.js"></script>
    <script src="/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="/assets/vendor/counterup/counterup.min.js"></script>
    <script src="/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="/assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="/assets/js/main.js"></script>
    <script type="text/javascript" src="~/js/script.js"></script>

</body>

</html>